### ISSUE TITLE
Can not run train_model.py

### ISSUE THREAD

**Issue by Eavie** [ayush1997/Xvision#3]
Hello PHD,
I am trying to 
python train_model.py <Training images folder> <Train images codes folder> <Training image labels file> <Folder to save models>

The problem is :
['DeepLearning/train_model.py', 'final_train_images_calc_nodule_only/', 'train-code/', 'training_labels_calc_nodule_only', 'xx.models']
train_labels 177
161
Traceback (most recent call last):
  File "DeepLearning/train_model.py", line 174, in <module>
    sess2.run(tf.initialize_all_variables())

Thanks!

**Comment by Eavie** [comment]
it seems like the line failed: 
       _,l,w1,cst = sess2.run([optimizer,train_label,W_1,Cost], feed_dict={x: content_features, y:label})

Traceback (most recent call last):
  File "DeepLearning/train_model.py", line 206, in <module>
    _,l,w1,cst = sess2.run([optimizer,train_label,W_1,Cost], feed_dict={x: content_features, y:label})
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: logits and labels must be same size: logits_size=[19,2] labels_size=[20,2]
	 [[Node: SoftmaxCrossEntropyWithLogits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](output/BiasAdd, _recv_Placeholder_1_0)]]
Caused by op u'SoftmaxCrossEntropyWithLogits', defined at:
  File "DeepLearning/train_model.py", line 149, in <module>
    Cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(h_3, y))
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 223, in softmax_cross_entropy_with_logits
    logits, labels, name=name)
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 873, in _softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()
Thanks !Please

**Comment by ayush1997** [comment]
Hi @Eavie 
The problem seems in
`tensorflow.python.framework.errors.InvalidArgumentError: logits and labels must be same size: logits_size=[19,2] labels_size=[20,2]`
The size are not same
can you give whole console output with the traceback !

**Comment by Eavie** [comment]
i changed this line : 
with tf.Session(graph=g2) as sess2, g2.device('/cpu:0'):




 $ python DeepLearning/train_model.py final_train_images_calc_nodule_only/ train-code/ training_labels_calc_nodule_only xx.model
/home/justinwan/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
['DeepLearning/train_model.py', 'final_train_images_calc_nodule_only/', 'train-code/', 'training_labels_calc_nodule_only', 'xx.model']
train_labels 177
+++++++++++=
161
(19, 25088) Feature Map Shape
j= 0
----------
(20, 2)
Traceback (most recent call last):
  File "DeepLearning/train_model.py", line 206, in <module>
    _,l,w1,cst = sess2.run([optimizer,train_label,W_1,Cost], feed_dict={x: content_features, y:label})
  File "/home/justinwan/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/home/justinwan/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/home/justinwan/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/home/justinwan/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: logits and labels must be same size: logits_size=[19,2] labels_size=[20,2]
	 [[Node: SoftmaxCrossEntropyWithLogits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](output/BiasAdd, _recv_Placeholder_1_0)]]
Caused by op u'SoftmaxCrossEntropyWithLogits', defined at:
  File "DeepLearning/train_model.py", line 149, in <module>
    Cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(h_3, y))
  File "/home/justinwan/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 223, in softmax_cross_entropy_with_logits
    logits, labels, name=name)
  File "/home/justinwan/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 873, in _softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "/home/justinwan/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/home/justinwan/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/justinwan/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()


 
------------------ Original ------------------

**Comment by ayush1997** [comment]
are you sure you have run the `train.py` file properly bcs there is issue with size of matrix stored in `'train-code/'` it shld be 20

**Comment by Eavie** [comment]
Hi,@ayush1997
here is my full test
$ python DeepLearning/train.py final_train_images_calc_nodule_only/ final_test_images_calc_nodule_only/ train-code test-code 
['DeepLearning/train.py', 'final_train_images_calc_nodule_only/', 'final_test_images_calc_nodule_only/', 'train-code', 'test-code']
161
j= 0
(19, 224, 224, 3) Image Shape
(19, 7, 7, 512)
(19, 7, 7, 512)
(19, 25088) Feature Map Shape
--- 22.0510749817 seconds ---
j= 20
(19, 224, 224, 3) Image Shape
(19, 7, 7, 512)
(19, 7, 7, 512)
(19, 25088) Feature Map Shape
--- 21.7819910049 seconds ---
j= 40
(19, 224, 224, 3) Image Shape
(19, 7, 7, 512)
(19, 7, 7, 512)
(19, 25088) Feature Map Shape
--- 21.6549859047 seconds ---
j= 60
(19, 224, 224, 3) Image Shape
(19, 7, 7, 512)
(19, 7, 7, 512)
(19, 25088) Feature Map Shape
--- 21.4256839752 seconds ---
j= 80
(19, 224, 224, 3) Image Shape
(19, 7, 7, 512)
(19, 7, 7, 512)
(19, 25088) Feature Map Shape
--- 21.2485909462 seconds ---
j= 100
(19, 224, 224, 3) Image Shape
(19, 7, 7, 512)
(19, 7, 7, 512)
(19, 25088) Feature Map Shape
--- 21.7770569324 seconds ---
j= 120
(19, 224, 224, 3) Image Shape
(19, 7, 7, 512)
(19, 7, 7, 512)
(19, 25088) Feature Map Shape
--- 22.0091180801 seconds ---
j= 140
(19, 224, 224, 3) Image Shape
(19, 7, 7, 512)
(19, 7, 7, 512)
(19, 25088) Feature Map Shape
--- 21.3194181919 seconds ---
3
j= 160
(16, 224, 224, 3) Image Shape
(16, 7, 7, 512)
(16, 7, 7, 512)
(16, 25088) Feature Map Shape
--- 19.2059268951 seconds ---
76
j= 0
(22, 7, 7, 512)
(22, 7, 7, 512)
test (22, 25088)
new test (22, 25088)
--- 25.0403130054 seconds ---
j= 25
(22, 7, 7, 512)
(22, 7, 7, 512)
test (22, 25088)
new test (22, 25088)
--- 25.0115730762 seconds ---
j= 50
(22, 7, 7, 512)
(22, 7, 7, 512)
test (22, 25088)
new test (22, 25088)
--- 24.9072268009 seconds ---
24
j= 75
(1, 7, 7, 512)
(1, 7, 7, 512)
test (1, 25088)
new test (1, 25088)
--- 5.47832393646 seconds ---

I think i have run python the train.py successfully. Because i got the two folders：
train-code/ and test-code/
$ls train-code/
0  100  120  140  160  20  40  60  80
$ ls test-code/
0  25  50  75

**Comment by salmonQ** [comment]
@Eavie I think you should make sure m=0 befor "for i in range (j+0,j+20-m)" untill j==r-1

**Comment by ayush1997** [comment]
Thanks @salmonQ, @Eavie sorry or such a delayed reply,I have made some changes in the code.
It is tested on Tensorflow1.12 and Python2.7
