### ISSUE TITLE
can not run train.py

### ISSUE THREAD

**Issue by umar-sharif** [ayush1997/Xvision#4]
Hi,
I'm trying to run train.py and getting following error

161
j= 0
(20, 224, 224, 3) Image Shape
Traceback (most recent call last):
  File train.py", line 131, in <module>
    content_features =get_content_feature(img_4d).reshape((get_content_feature(img_4d).shape[0],7*7*512))
  **File "train.py", line 87, in get_content_feature    'vgg/dropout/random_uniform:0': [[1.0]]**
  File "tensorflow\python\framework\ops.py", line 575, in eval    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "tensorflow\python\framework\ops.py", line 3633, in _eval_using_default_session    return session.run(tensors, feed_dict)
  File "tensorflow\python\client\session.py", line 766, in run    run_metadata_ptr)
  File "tensorflow\python\client\session.py", line 943, in _run   % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
**ValueError: Cannot feed value of shape (1, 1) for Tensor 'vgg/dropout/random_uniform:0', which has shape '(?, 4096)'**

Could you help me with this. I'm new to python.

Thanks.

**Comment by ayush1997** [comment]
Hi @umar-sharif 
sry for late reply which tensorflow version are you using.

**Comment by umar-sharif** [comment]
Hi @ayush1997 
I'm using tensorflow 0.12 and python 3.5

**Comment by salmonQ** [comment]
@umar-sharif 
I've met the same problem。
solved it by changing codes 'vgg/dropout/random_uniform:0':[[1.0]] into 'vgg/dropout/random_uniform:0':[[1.0]*4096]

**Comment by prateeknepaliya09** [comment]
@salmonQ   I have made the following changes, same error. Any inputs?

**Comment by prateeknepaliya09** [comment]
@ayush1997 Can you look into it?

**Comment by ayush1997** [comment]
@umar-sharif @salmonQ @prateeknepaliya09 sorry for such a late reply,have made some changes.
It is tested on Tensorflow1.12 and Python 2.7
