### ISSUE TITLE
Error while running test_model.py : Incompatible shapes

### ISSUE THREAD

**Issue by erravigoyal** [ayush1997/Xvision#7]
Hi Ayush,

I am getting below error while running test_model.py. Could you help me on this please ? I have Python 3.2.5 and tensorflow 1.0 on Windows platform.

Traceback (most recent call last):
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\client\session.py", line 1022, in _do_call
    return fn(*args)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\client\session.py", line 1004, in _run_fn
    status, run_metadata)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\contextlib.py", li
ne 66, in __exit__
    next(self.gen)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_
status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shape
s: [9] vs. [25]
         [[Node: Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/tas
k:0/cpu:0"](ArgMax_1, ArgMax_2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_model.py", line 189, in <module>
    acc,pred,s,actual = sess1.run([accuracy,predicted_y,soft,actual_y], feed_dic
t={x: content_features,y: test_label})
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shape
s: [9] vs. [25]
         [[Node: Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/tas
k:0/cpu:0"](ArgMax_1, ArgMax_2)]]

Caused by op 'Equal', defined at:
  File "test_model.py", line 153, in <module>
    correct_prediction = tf.equal(predicted_y, actual_y)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\ops\gen_math_ops.py", line 721, in equal
    result = _op_def_lib.apply_op("Equal", x=x, y=y, name=name)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tens
orflow\python\framework\ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\goyalr\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1264, in __init__    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [9] vs. [25]
         [[Node: Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"](ArgMax_1, ArgMax_2)]]

**Comment by prateeknepaliya09** [comment]
@erravigoyal you managed to resolve it?

**Comment by ayush1997** [comment]
Hi @erravigoyal  @prateeknepaliya09 sorry for a such a delayed reply.I recently looked into the issue and have made some changes in the code.It is tested on Tensorflow 1.12 and python2.7
